### PR TITLE
web-ui: fix server request, close #186

### LINKED ISSUE #186: Fix server request in UI
The web ui currently only sends the link from textbox. The api definition from the link should be fetched first and then send to the server.

### PR DESCRIPTION
**Pull request by rbarilani**
fix server request, close #186
fetch the schema, transform to json and send the request to zally api server.

### CODE REVIEW

**Comment by fmueller** [comment]
I excluded `web-ui` project folder from codacy analysis. Just do a dummy commit on this branch - so Codacy will start again.

File: web-ui/src/server/fetch.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+const fetch = require('node-fetch');
+
+function handleResponse(response) {
+  if (response.status >= 200 && response.status < 300) {
```
Comment (mfellner) [inline web-ui/src/server/fetch.js]: I wouldn't reject HTTP codes in the 100 and 300 ranges as errors, because they're not. Technically, only 400 and up are considered errors.

File: web-ui/src/server/fetch.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    return Promise.resolve(response)
+  } else {
+    var error = new Error(response.statusText || response.status);
+    error.response = response;
```
Comment (mfellner) [inline web-ui/src/server/fetch.js]: Adding the complete response object to the error might be a bit much.  If we only the the status code then let's try this:

```javascript
error.status = response.statusCode || response.status || 500;
```

File: web-ui/src/server/zally-api-handler.js [hunk 3]
```diff
@@ -1,9 +1,59 @@
...
-  var url = env.ZALLY_API_URL + req.url.replace('/zally-api', '');
-  logger.debug(`Proxying request to: ${url}`);
-  req.pipe(request(url)).pipe(res);
+  const url = env.ZALLY_API_URL + req.url.replace('/zally-api', '');
+  const apiDefinitionURL = req.body.api_definition;
+
+  logger.debug(`Fetch swagger schema: ${apiDefinitionURL}`);
+
+  fetch(apiDefinitionURL)
+    .then((response) => {
```
Comment (mfellner) [inline web-ui/src/server/zally-api-handler.js]: I'd recommend upgrading to Node 7.6+ (by requiring it in [package.json](https://docs.npmjs.com/files/package.json#engines)) and use async/await in this function to avoid nesting. We're already using node:7.7-cd45 in the Dockerfile so we're good to go.

File: web-ui/src/server/zally-api-handler.js [hunk 4]
```diff
@@ -1,9 +1,59 @@
...
+  } catch(err) {}
+
+  return yaml.safeLoad(text);
+};
 
 module.exports = function (req, res) {
-  var url = env.ZALLY_API_URL + req.url.replace('/zally-api', '');
-  logger.debug(`Proxying request to: ${url}`);
-  req.pipe(request(url)).pipe(res);
+  const url = env.ZALLY_API_URL + req.url.replace('/zally-api', '');
```
Comment (mfellner) [inline web-ui/src/server/zally-api-handler.js]: It wasn't any clearer before, but maybe let's add at least a comment to understand what url we're actually creating here.

File: web-ui/src/server/zally-api-handler.js [hunk 5]
```diff
@@ -1,9 +1,59 @@
 const env = require('./env');
 const logger = require('./logger');
-const request = require('request');
+const fetch = require('./fetch');
+const yaml = require('js-yaml');
+
+const parseSchema = (text) => {
```
Comment (mfellner) [inline web-ui/src/server/zally-api-handler.js]: Let's keep our style consistent and use proper function declaration, i.e. `function name { }`, when declaring functions.

**Comment by mfellner** [comment]
👍

**Comment by rbarilani** [comment]
👍

**Comment by fmueller** [comment]
As discussed, travis is read because it has some network issues and we still have an unwanted integration with codacy.
