### PR TITLE
182 Fix ProblemJson Rule

### LINKED ISSUE #182: UseProblemJsonRule is incorrect
Current implementation of UseProblemJsonRule is incorrect:
```
if (httpCode in 400..599 && responseEntry.value?.schema?.type != "ref") { //TODO MK: implement real check for Problem usage
    listOf("${pathEntry.key} ${opEntry.key} ${responseEntry.key}")
} else emptyList()
```

It checks only for `schema.type` being ref. 

*DoD:*
UseProblemJsonRule checks whether error response is json object with problem structure (including ref to such object)

### PR DESCRIPTION
**Pull request by netme**
Closes #182

### CODE REVIEW

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 1]
```diff
@@ -35,4 +40,17 @@ class UseProblemJsonRule : AbstractRule() {
             } catch (nfe: NumberFormatException) {
                 null
             }
+
+    private fun isProperRef(response: Response) : Boolean {
+        return if (response.schema?.type == "ref") {
+            val schema : RefProperty = response.schema as RefProperty
+            (schema.`$ref` == "#/definitions/Problem")
```
Comment (netme) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: Unfortunately, swagger parser imports the ref and marks it as internal, that's why I also need to check fields set.

**Comment by fmueller** [comment]
👍

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 2]
```diff
@@ -35,4 +40,17 @@ class UseProblemJsonRule : AbstractRule() {
...
+        } else {
+            false
+        }
+    }
+
+    private fun isProblemDefinitionCorrect(definition: Model?) : Boolean {
+        return (definition?.properties?.keys == setOf("type", "title", "status", "detail", "instance"))
```
Comment (fmueller) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: Does this mean, I only can have these fields in the problem object or does this mean at least these field? The latter one is correct because you are allowed to extend the problem object according to your needs.

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt (hunk 1 above)
Comment (fmueller) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: Ok ;)

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt (hunk 2 above)
Comment (netme) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: I see, then some adjustments are still needed. Will do it.

**Comment by netme** [comment]
@fmueller , I've addressed your comments in  6d7cc5c...d7b7cb7

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 3]
```diff
@@ -35,4 +42,32 @@ class UseProblemJsonRule : AbstractRule() {
             } catch (nfe: NumberFormatException) {
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: In Kotlin 1.1 method `String.toIntOrNull()` is in standard library. Our custom method can be removed.

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 4]
```diff
@@ -35,4 +42,32 @@ class UseProblemJsonRule : AbstractRule() {
...
                 null
             }
+
+    private fun isProperRef(swagger: Swagger, response: Response) : Boolean {
+        return if (response.schema?.type == "ref") {
+            val schema : RefProperty = response.schema as RefProperty
+            return isProblemDefinitionCorrect(swagger, swagger.definitions[schema.simpleRef])
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: `return` can be removed here

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 5]
```diff
@@ -35,4 +42,32 @@ class UseProblemJsonRule : AbstractRule() {
             } catch (nfe: NumberFormatException) {
                 null
             }
+
+    private fun isProperRef(swagger: Swagger, response: Response) : Boolean {
+        return if (response.schema?.type == "ref") {
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: Seems like current implementation prohibits inlined Problem definition. 
1. Is it true? 
2. If yes, do we want to support this usecase?

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 6]
```diff
@@ -35,4 +42,32 @@ class UseProblemJsonRule : AbstractRule() {
...
+            return isProblemDefinitionCorrect(swagger, swagger.definitions[schema.simpleRef])
+        } else {
+            false
+        }
+    }
+
+    private fun isProblemDefinitionCorrect(swagger: Swagger, definition: Model?) : Boolean {
+        val properties = getProperties(swagger, definition)
+        return requiredFields.filter { field -> !properties.contains(field) }.isEmpty()
+    }
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: I propose to do this:
```
private fun isProblemDefinitionCorrect(swagger: Swagger, definition: Model?) = getProperties(swagger, definition).containsAll(requiredFields)
```
and inline this method.

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt [hunk 7]
```diff
@@ -35,4 +42,32 @@ class UseProblemJsonRule : AbstractRule() {
...
+
+    private fun getProperties(swagger: Swagger, definition: Model?) : Set<String> {
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: I propose to implement it like that to avoid nested `when`:
```
private fun getProperties(swagger: Swagger, definition: Model?): Set<String> =
        when (definition) {
            is ComposedModel -> definition.allOf.orEmpty().flatMap { getProperties(swagger, it) }.toSet()
            is RefModel -> getProperties(swagger, swagger.definitions[definition.simpleRef])
            else -> definition?.properties?.keys.orEmpty()
        }
```
For me it looks a bit more readable.

File: server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt (hunk 5 above)
Comment (netme) [inline server/src/main/java/de/zalando/zally/rules/UseProblemJsonRule.kt]: @mkulak , fair point, implemented in c5710b7

**Comment by netme** [comment]
@mkulak , many thanks for your valuable comments, I've learned something and addressed them in aa7d6bd

**Comment by mkulak** [comment]
:+1:
