### PR TITLE
Fix handling of whitelisted property names

### LINKED ISSUE #96: _links field is not whitelisted
_links field should be whitelisted in each rule, it violates our syntax rules in the guidelines but is also defined as default field for links in our guidelines. Currently Zally creates violations for it.

### PR DESCRIPTION
**Pull request by fmueller**
Closes #96

### CODE REVIEW

File: server/src/main/java/de/zalando/zally/rules/SnakeCaseInPropNameRule.kt [hunk 1]
```diff
@@ -16,9 +16,11 @@ class SnakeCaseInPropNameRule : AbstractRule() {
     override val code = "M012"
     val description = "Property names must be snake_case (and never camelCase)"
 
+    private val whitelist = setOf("_links")
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/SnakeCaseInPropNameRule.kt]: I think this value should be in config. You can find example in `AvoidJavascriptKeywordsRule`

File: server/src/main/java/de/zalando/zally/rules/SnakeCaseInPropNameRule.kt [hunk 2]
```diff
@@ -16,9 +16,11 @@ class SnakeCaseInPropNameRule : AbstractRule() {
...
+
     override fun validate(swagger: Swagger): Violation? {
         val result = swagger.getAllJsonObjects().flatMap { (def, path) ->
-            val badProps = def.keys.filterNot(PatternUtil::isSnakeCase)
+            val badProps = def.keys.filterNot { d -> PatternUtil.isSnakeCase(d) || whitelist.contains(d) }
```
Comment (mkulak) [inline server/src/main/java/de/zalando/zally/rules/SnakeCaseInPropNameRule.kt]: This can also be written as:
```
val badProps = def.keys.filterNot { PatternUtil.isSnakeCase(it) || it in whitelist }
```
(not insisting, just FYI)

**Comment by fmueller** [comment]
@mkulak I incorporated your points. :)

**Comment by mkulak** [comment]
👍
